### ISSUE TITLE
Basic Extractor import failed

### ISSUE THREAD

**Issue by jimhavrilla** [GeneDx/txt2hpo#47] opened 2021-03-05 05:16 UTC
Version: `0.2.2` installed by pip

This required file no longer exists, causing your tool to fail:
http://compbio.charite.de/jenkins/job/hpo.annotations.current/lastStableBuild/artifact/current/phenotype.hpoa

Only ran:
```
from txt2hpo.extract import Extractor
```

Cheers.

P.S. Are there any comparisons in accuracy between this tool and QuickUMLS + spaCy, cTakes, CLAMP, ClinPhen or similar?

**Comment by jimhavrilla** [comment] 2021-03-05 05:35
Also tried `python -m pip install git+https://github.com/GeneDx/txt2hpo.git@develop` because I was curious but ran into odd spaCy dependency issues:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
en-core-web-sm 3.0.0 requires spacy<3.1.0,>=3.0.0, but you have spacy 2.2.4 which is incompatible.
```

**Comment by vgainullin** [comment] 2021-03-05 06:02
Thanks for reporting this issue. Unfortunately, the missing file dependency is affecting a txt2hpo dependency (phenopy), which is yet to be updated on pypi. Until this happens, you have to:
1) pip uninstall phenopy
2) rm ~/.phenopy
3) python -m pip install git+https://github.com/GeneDx/phenopy.git@develop
4) pip uninsall txt2hpo
5) rm ~/.txt2hpo
6) git clone https://github.com/GeneDx/txt2hpo
7) cd txt2hpo && python setup.py install

Sorry for the inconvenience, we are working on a release to fix these install issues soon. 

Regarding comparing txt2hpo to other EHR extraction. I am not aware of another HPO extraction tool, which would be easily deployed with python to allow proper benchmarking.

**Comment by jimhavrilla** [comment] 2021-03-05 06:10
Wow, that was a lot haha.  Please let me know when you have updated the phenopy pypi package.  I'd like to make this installation process a bit more reproducible for future pipeline users 😁 

ClinPhen has a pip install, and with some finagling QuickUMLS (which also has a pip install) can be converted from UMLS to HPO.

**Comment by jimhavrilla** [comment] 2021-03-08 23:29
Yeah I guess typos aren't so critical but it would be a shame to miss
terms. Appreciate it.

Jim Havrilla

**Comment by jimhavrilla** [comment] 2021-03-08 23:30
Actually, iterating through 5 dict entries with note free text takes 37
seconds on one core. How do you recommend parallelizing? Multiprocessing
module?

Jim Havrilla

**Comment by vgainullin** [comment] 2021-03-08 23:38
Could you elaborate on what amount of text takes 37 seconds to process? Yes, multiprocessing module should do the trick. Happy to provide examples.

**Comment by jimhavrilla** [comment] 2021-03-08 23:54
5 blocks of text of >2000 characters.

Please do. Whatever you find optimal I'd love to hear it.

Jim Havrilla

**Comment by vgainullin** [comment] 2021-03-10 00:37
Must be significantly more than 2000 characters. Below are preferred settings and some multiprocessing code.
Please let me know if you run into more issues. 

```
from txt2hpo.extract import Extractor
ex = Extractor(correct_spelling=False, max_neighbors=2)
```

```
%%time
from multiprocessing import Pool
def hpos(text):
    return ex.hpo(text).json
ncpus=32
text =["hypotonia, developmental delay and deafness "*1000]*200
pool = Pool(ncpus)
done = []
for res in pool.map(hpos, text):
    done.append(res)

pool.close()
```

CPU times: user 66 ms, sys: 558 ms, total: 624 ms
Wall time: 2.7 s

**Comment by jimhavrilla** [comment] 2021-03-10 22:56
Exactly what I was thinking.  Great, thanks.  By the way, this software
will likely stay CC BY-NC-SA 4.0 license, right?

**Comment by vgainullin** [comment] 2021-03-12 14:47
Yes, we are unlikely to change the license any time soon.

**Comment by vgainullin** [comment] 2021-03-12 14:49
Also, please note the snipped above will extract negated terms. To remove negated use:
```
ex = Extractor(correct_spelling=False, max_neighbors=2, remove_negated=True)
```
this will likely add significant extra processing time.

**Comment by jimhavrilla** [comment] 2021-03-22 08:52
Just wanted to tell you I tried a fresh pip install of `txt2hpo` (Mar8 2021 ver) and this happened:
```
  File "dstest/runt2h.py", line 1, in <module>
    from txt2hpo.extract import Extractor
  File "/home/havrillaj/miniconda3/envs/phen2gene/lib/python3.8/site-packages/txt2hpo/extract.py", line 7, in <module>
    from txt2hpo.build_tree import update_progress, hpo_network
  File "/home/havrillaj/miniconda3/envs/phen2gene/lib/python3.8/site-packages/txt2hpo/build_tree.py", line 5, in <module>
    from txt2hpo.util import hpo_network
  File "/home/havrillaj/miniconda3/envs/phen2gene/lib/python3.8/site-packages/txt2hpo/util.py", line 14, in <module>
    obo_file = config.get('hpo', 'obo')
  File "/home/havrillaj/miniconda3/envs/phen2gene/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/home/havrillaj/miniconda3/envs/phen2gene/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'hpo
```
Looks like it may not be grabbing the correct obo file or something?

Old install still works.  Also noticed pip wheel did not grab `phenopy` if that was something that was supposed to be fixed.

**Comment by vgainullin** [comment] 2021-03-22 12:57
Hi Jim, 
I think this is caused by presence of a config from the previous version in your ~/.txt2hpo directory. To fix this please delete your ~/.txt2hpo and reinstall fresh txt2hpo from pip. 
```rm -r ~/.txt2hpo```

**Comment by jimhavrilla** [comment] 2021-03-22 13:00
No, this was in a fresh conda environment.

**Comment by vgainullin** [comment] 2021-03-22 13:10
I dont think conda environments have any effect on your dot files. You can check with `ls -lht ~/.txt2hpo`. Your txt2hpo.ini config likely predates the new version.

**Comment by jimhavrilla** [comment] 2021-03-22 20:16
Wow, really?  It did seem to fix the problem, but that means whenever you install the module, the first install is the only one that matters?  Isn't that an issue for distribution, or utilization of different environments/paths?  Since it was in this instance.  Or is this no longer and issue going forward with the new dist?

**Comment by vgainullin** [comment] 2021-03-22 20:27
The dot files are used primarily to customize your installation. I am not sure this really causes many issues unless one isn't aware of them. Maybe I should mention them in the README :).

**Comment by jimhavrilla** [comment] 2021-03-22 20:29
One last question (then I guess we should probably close the issue), which is a greater speed decrease, negation removal, or spelling check?

**Comment by vgainullin** [comment] 2021-03-22 20:40
Removing negated terms is bar far the most time-consuming part, currently.

**Comment by jimhavrilla** [comment] 2021-03-22 20:42
Oh, I see. That's the part I care about most. Oh well, will still use that
feature.

Jim Havrilla

**Comment by vgainullin** [comment] 2021-03-22 20:44
Hopefully I can optimize this feature in the next iteration. Feel free to create a ticket.

**Comment by jimhavrilla** [comment] 2021-03-22 22:25
Sounds good. Been a pleasure talking to you.

Jim Havrilla

**Comment by vgainullin** [comment] 2021-03-23 14:43
Thanks for the input, closing the issue.

**Closed by vgainullin** 2021-03-23 14:43 UTC
